name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS latest (works well with newer Xcode versions)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to set up the correct Xcode version explicitly
    - name: Set up Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    # Clean the derived data before building
    - name: Clean derived data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*

    # Step to explicitly select Xcode 16.2
    - name: Set Xcode version to 16.2
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    # Step to ensure the iOS Simulator boots correctly
    - name: Boot iOS Simulator
      run: |
        xcrun simctl boot "iPhone 16"

    # Build and test step
    - name: Build and test
      run: |
        xcodebuild -version
        xcodebuild test -project CloudKitNotes.xcodeproj -scheme CloudKitNotesTests -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.3.1' test
