name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

      
jobs:
  build:
    runs-on: macos-latest  # or specify a version, e.g., macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensure you fetch the latest repo

      - name: Set up Xcode
        uses: actions/setup-xcode@v3  # Official GitHub action

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install Dependencies
        run: |
          brew install cocoapods
          pod install
