name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set Up Xcode
        uses: actions/setup-xcode@v4
        with:
          xcode-version: '16.2'

      - name: Run Tests
        run: |
          xcodebuild -workspace CloudKitNotes.xcworkspace -scheme CloudKitNotesTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' test | xcpretty