name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Explicitly use macOS 14 (Sonoma)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Build and test
      run: |
        xcodebuild -version
        xcodebuild test -project CloudKitNotes.xcodeproj -scheme CloudKitNotesTests -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.3.1' test